/**
 * RSES CMS Base Theme Manifest
 *
 * This is the foundational theme that all other themes extend.
 * It provides sensible defaults and a complete token system.
 */

import type { ThemeManifest } from '../../types';

export const baseThemeManifest: ThemeManifest = {
  name: 'base',
  displayName: 'Base Theme',
  description: 'The foundational RSES CMS theme. Provides sensible defaults that other themes extend.',
  version: '1.0.0',
  author: {
    name: 'RSES CMS',
    url: 'https://rses-cms.io',
  },
  coreVersion: '1.x',

  features: {
    colorModes: true,
    responsive: true,
    rtl: true,
    highContrast: true,
    reducedMotion: true,
    customFonts: true,
    settingsUI: true,
    hotReload: true,
  },

  regions: {
    page_top: {
      name: 'page_top',
      label: 'Page Top',
      description: 'Very top of page (skip links, announcements)',
      weight: -100,
    },
    header: {
      name: 'header',
      label: 'Header',
      description: 'Main header area',
      element: 'header',
      role: 'banner',
      gridArea: 'header',
      weight: 0,
    },
    navigation: {
      name: 'navigation',
      label: 'Navigation',
      description: 'Primary navigation',
      element: 'nav',
      role: 'navigation',
      ariaLabel: 'Main navigation',
      weight: 10,
    },
    breadcrumb: {
      name: 'breadcrumb',
      label: 'Breadcrumb',
      description: 'Breadcrumb navigation',
      element: 'nav',
      role: 'navigation',
      ariaLabel: 'Breadcrumb',
      weight: 20,
    },
    messages: {
      name: 'messages',
      label: 'Messages',
      description: 'System messages',
      role: 'status',
      weight: 25,
    },
    sidebar_left: {
      name: 'sidebar_left',
      label: 'Left Sidebar',
      description: 'Left sidebar area',
      element: 'aside',
      role: 'complementary',
      gridArea: 'sidebar-left',
      weight: 30,
    },
    content: {
      name: 'content',
      label: 'Content',
      description: 'Main content area',
      required: true,
      element: 'main',
      role: 'main',
      gridArea: 'content',
      weight: 50,
    },
    sidebar_right: {
      name: 'sidebar_right',
      label: 'Right Sidebar',
      description: 'Right sidebar area',
      element: 'aside',
      role: 'complementary',
      gridArea: 'sidebar-right',
      weight: 70,
    },
    footer: {
      name: 'footer',
      label: 'Footer',
      description: 'Page footer',
      element: 'footer',
      role: 'contentinfo',
      gridArea: 'footer',
      weight: 100,
    },
    page_bottom: {
      name: 'page_bottom',
      label: 'Page Bottom',
      description: 'Very bottom of page',
      weight: 200,
    },
  },

  tokens: {
    colors: {
      primitives: {
        neutral: {
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
          950: '#09090b',
        },
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        accent: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c22c9',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        info: {
          50: '#ecfeff',
          100: '#cffafe',
          200: '#a5f3fc',
          300: '#67e8f9',
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
          700: '#0e7490',
          800: '#155e75',
          900: '#164e63',
          950: '#083344',
        },
      },
      semantic: {
        background: '{colors.primitives.neutral.50}',
        foreground: '{colors.primitives.neutral.950}',
        card: '#ffffff',
        cardForeground: '{colors.primitives.neutral.950}',
        popover: '#ffffff',
        popoverForeground: '{colors.primitives.neutral.950}',
        primary: '{colors.primitives.primary.600}',
        primaryForeground: '#ffffff',
        secondary: '{colors.primitives.secondary.100}',
        secondaryForeground: '{colors.primitives.secondary.900}',
        muted: '{colors.primitives.neutral.100}',
        mutedForeground: '{colors.primitives.neutral.500}',
        accent: '{colors.primitives.accent.100}',
        accentForeground: '{colors.primitives.accent.900}',
        destructive: '{colors.primitives.error.600}',
        destructiveForeground: '#ffffff',
        success: '{colors.primitives.success.600}',
        successForeground: '#ffffff',
        warning: '{colors.primitives.warning.500}',
        warningForeground: '{colors.primitives.neutral.950}',
        info: '{colors.primitives.info.600}',
        infoForeground: '#ffffff',
        border: '{colors.primitives.neutral.200}',
        borderSubtle: '{colors.primitives.neutral.100}',
        input: '{colors.primitives.neutral.200}',
        inputForeground: '{colors.primitives.neutral.950}',
        ring: '{colors.primitives.primary.500}',
        selection: '{colors.primitives.primary.100}',
        selectionForeground: '{colors.primitives.primary.900}',
        link: '{colors.primitives.primary.600}',
        linkHover: '{colors.primitives.primary.700}',
        linkVisited: '{colors.primitives.accent.600}',
        codeBackground: '{colors.primitives.neutral.100}',
        codeForeground: '{colors.primitives.neutral.800}',
      },
    },

    spacing: {
      unit: '0.25rem',
      scale: {
        '0': '0',
        'px': '1px',
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '2.5': '0.625rem',
        '3': '0.75rem',
        '3.5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      semantic: {
        pageMargin: '1.5rem',
        sectionGap: '3rem',
        contentMaxWidth: '80rem',
        cardPadding: '1.5rem',
        inputPaddingX: '0.75rem',
        inputPaddingY: '0.5rem',
        buttonPaddingX: '1rem',
        buttonPaddingY: '0.5rem',
        stackGap: '1rem',
        inlineGap: '0.5rem',
        gridGap: '1.5rem',
      },
    },

    typography: {
      families: {
        sans: {
          family: 'Inter',
          fallbacks: ['system-ui', '-apple-system', 'sans-serif'],
        },
        serif: {
          family: 'Georgia',
          fallbacks: ['Cambria', 'serif'],
        },
        mono: {
          family: 'JetBrains Mono',
          fallbacks: ['Menlo', 'Monaco', 'monospace'],
        },
      },
      sizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
        '8xl': '6rem',
        '9xl': '8rem',
      },
      weights: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        black: 900,
      },
      lineHeights: {
        none: 1,
        tight: 1.25,
        snug: 1.375,
        normal: 1.5,
        relaxed: 1.625,
        loose: 2,
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      styles: {
        h1: { fontSize: '2.25rem', fontWeight: 700, lineHeight: 1.25, letterSpacing: '-0.025em' },
        h2: { fontSize: '1.875rem', fontWeight: 600, lineHeight: 1.3, letterSpacing: '-0.025em' },
        h3: { fontSize: '1.5rem', fontWeight: 600, lineHeight: 1.375 },
        h4: { fontSize: '1.25rem', fontWeight: 600, lineHeight: 1.4 },
        h5: { fontSize: '1.125rem', fontWeight: 600, lineHeight: 1.4 },
        h6: { fontSize: '1rem', fontWeight: 600, lineHeight: 1.5 },
        body: { fontSize: '1rem', fontWeight: 400, lineHeight: 1.5 },
        bodySmall: { fontSize: '0.875rem', fontWeight: 400, lineHeight: 1.5 },
        bodyLarge: { fontSize: '1.125rem', fontWeight: 400, lineHeight: 1.6 },
        caption: { fontSize: '0.75rem', fontWeight: 400, lineHeight: 1.4 },
        overline: { fontSize: '0.75rem', fontWeight: 500, lineHeight: 1.4, letterSpacing: '0.05em', textTransform: 'uppercase' },
        label: { fontSize: '0.875rem', fontWeight: 500, lineHeight: 1.4 },
        button: { fontSize: '0.875rem', fontWeight: 500, lineHeight: 1.25 },
        code: { fontSize: '0.875rem', fontWeight: 400, lineHeight: 1.5, fontFamily: 'var(--font-mono)' },
      },
    },

    shadows: {
      scale: {
        none: 'none',
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        base: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
      },
      semantic: {
        card: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        dropdown: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        modal: '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        toast: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        buttonHover: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
        focusRing: '0 0 0 2px var(--color-ring)',
      },
    },

    borders: {
      radius: {
        none: '0',
        sm: '0.125rem',
        base: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      width: {
        none: '0',
        hairline: '0.5px',
        thin: '1px',
        base: '1px',
        thick: '2px',
      },
      semantic: {
        button: '0.375rem',
        input: '0.375rem',
        card: '0.5rem',
        modal: '0.75rem',
        badge: '9999px',
        avatar: '9999px',
      },
    },

    motion: {
      duration: {
        instant: '0ms',
        fast: '100ms',
        normal: '200ms',
        slow: '300ms',
        slower: '500ms',
        slowest: '1000ms',
      },
      easing: {
        linear: 'linear',
        ease: 'ease',
        easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeOutBack: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        easeInBack: 'cubic-bezier(0.36, 0, 0.66, -0.56)',
        bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
      reducedMotion: {
        duration: '0ms',
        easing: 'linear',
      },
    },

    zIndex: {
      scale: {
        hide: -1,
        base: 0,
        dropdown: 1000,
        sticky: 1100,
        fixed: 1200,
        overlay: 1300,
        modal: 1400,
        popover: 1500,
        toast: 1600,
        tooltip: 1700,
        maximum: 9999,
      },
    },

    opacity: {
      scale: {
        '0': 0,
        '5': 0.05,
        '10': 0.1,
        '20': 0.2,
        '25': 0.25,
        '30': 0.3,
        '40': 0.4,
        '50': 0.5,
        '60': 0.6,
        '70': 0.7,
        '75': 0.75,
        '80': 0.8,
        '90': 0.9,
        '95': 0.95,
        '100': 1,
      },
      semantic: {
        disabled: 0.5,
        placeholder: 0.5,
        overlay: 0.5,
        glass: 0.8,
      },
    },
  },

  libraries: {
    base: {
      id: 'base',
      description: 'Base theme styles',
      global: true,
      css: [
        { path: './css/variables.css', weight: -100, layer: 'base' },
        { path: './css/reset.css', weight: -90, layer: 'base' },
        { path: './css/typography.css', weight: -80, layer: 'base' },
        { path: './css/utilities.css', weight: 100, layer: 'utilities' },
      ],
    },
    components: {
      id: 'components',
      description: 'Base component styles',
      dependencies: [{ type: 'library', name: 'base' }],
      css: [
        { path: './css/components.css', weight: 0, layer: 'components' },
      ],
    },
  },

  settings: {
    groups: [
      {
        id: 'general',
        label: 'General',
        icon: 'Settings',
        settings: [
          {
            key: 'siteName',
            label: 'Site Name',
            type: 'text',
            default: 'RSES CMS',
          },
          {
            key: 'logoPath',
            label: 'Logo',
            type: 'image',
            default: '',
            options: { allowedTypes: ['image/png', 'image/svg+xml'] },
          },
        ],
      },
      {
        id: 'colors',
        label: 'Colors',
        icon: 'Palette',
        settings: [
          {
            key: 'primaryColor',
            label: 'Primary Color',
            type: 'color',
            default: '#3b82f6',
            token: 'colors.primitives.primary.500',
          },
          {
            key: 'accentColor',
            label: 'Accent Color',
            type: 'color',
            default: '#a855f7',
            token: 'colors.primitives.accent.500',
          },
        ],
      },
      {
        id: 'typography',
        label: 'Typography',
        icon: 'Type',
        settings: [
          {
            key: 'fontFamily',
            label: 'Font Family',
            type: 'font',
            default: 'Inter',
            options: {
              fontOptions: [
                { family: 'Inter', weights: [400, 500, 600, 700], category: 'sans-serif', source: 'google' },
                { family: 'Roboto', weights: [400, 500, 700], category: 'sans-serif', source: 'google' },
                { family: 'Open Sans', weights: [400, 600, 700], category: 'sans-serif', source: 'google' },
                { family: 'System UI', weights: [400, 500, 600, 700], category: 'sans-serif', source: 'system' },
              ],
            },
          },
          {
            key: 'fontSize',
            label: 'Base Font Size',
            type: 'number',
            default: 16,
            options: { min: 12, max: 24, step: 1, unit: 'px' },
          },
        ],
      },
      {
        id: 'layout',
        label: 'Layout',
        icon: 'Layout',
        settings: [
          {
            key: 'maxWidth',
            label: 'Max Content Width',
            type: 'number',
            default: 1280,
            options: { min: 800, max: 2000, step: 40, unit: 'px' },
          },
          {
            key: 'sidebarPosition',
            label: 'Sidebar Position',
            type: 'select',
            default: 'left',
            options: {
              choices: [
                { value: 'left', label: 'Left' },
                { value: 'right', label: 'Right' },
                { value: 'none', label: 'None' },
              ],
            },
          },
        ],
      },
    ],
    defaults: {
      siteName: 'RSES CMS',
      logoPath: '',
      primaryColor: '#3b82f6',
      accentColor: '#a855f7',
      fontFamily: 'Inter',
      fontSize: 16,
      maxWidth: 1280,
      sidebarPosition: 'left',
    },
  },

  breakpoints: {
    values: {
      xs: { minWidth: 0, label: 'Extra Small' },
      sm: { minWidth: 640, label: 'Small' },
      md: { minWidth: 768, label: 'Medium' },
      lg: { minWidth: 1024, label: 'Large' },
      xl: { minWidth: 1280, label: 'Extra Large' },
      '2xl': { minWidth: 1536, label: '2X Large' },
    },
    default: 'xs',
    containerQueries: true,
  },

  colorSchemes: {
    schemes: [
      {
        id: 'light',
        name: 'Light',
        className: 'light',
        icon: 'Sun',
        mediaQuery: '(prefers-color-scheme: light)',
      },
      {
        id: 'dark',
        name: 'Dark',
        className: 'dark',
        icon: 'Moon',
        mediaQuery: '(prefers-color-scheme: dark)',
        tokens: {
          colors: {
            primitives: {} as any, // Inherited
            semantic: {
              background: '{colors.primitives.neutral.950}',
              foreground: '{colors.primitives.neutral.50}',
              card: '{colors.primitives.neutral.900}',
              cardForeground: '{colors.primitives.neutral.50}',
              popover: '{colors.primitives.neutral.900}',
              popoverForeground: '{colors.primitives.neutral.50}',
              primary: '{colors.primitives.primary.500}',
              primaryForeground: '#ffffff',
              secondary: '{colors.primitives.secondary.800}',
              secondaryForeground: '{colors.primitives.secondary.100}',
              muted: '{colors.primitives.neutral.800}',
              mutedForeground: '{colors.primitives.neutral.400}',
              accent: '{colors.primitives.accent.800}',
              accentForeground: '{colors.primitives.accent.100}',
              destructive: '{colors.primitives.error.600}',
              destructiveForeground: '#ffffff',
              success: '{colors.primitives.success.500}',
              successForeground: '#ffffff',
              warning: '{colors.primitives.warning.500}',
              warningForeground: '{colors.primitives.neutral.950}',
              info: '{colors.primitives.info.500}',
              infoForeground: '#ffffff',
              border: '{colors.primitives.neutral.800}',
              borderSubtle: '{colors.primitives.neutral.800}',
              input: '{colors.primitives.neutral.800}',
              inputForeground: '{colors.primitives.neutral.50}',
              ring: '{colors.primitives.primary.500}',
              selection: '{colors.primitives.primary.900}',
              selectionForeground: '{colors.primitives.primary.100}',
              link: '{colors.primitives.primary.400}',
              linkHover: '{colors.primitives.primary.300}',
              linkVisited: '{colors.primitives.accent.400}',
              codeBackground: '{colors.primitives.neutral.800}',
              codeForeground: '{colors.primitives.neutral.200}',
            },
          },
          spacing: undefined as any,
          typography: undefined as any,
          shadows: {
            scale: {
              none: 'none',
              sm: '0 1px 2px 0 rgb(0 0 0 / 0.3)',
              base: '0 1px 3px 0 rgb(0 0 0 / 0.4), 0 1px 2px -1px rgb(0 0 0 / 0.4)',
              md: '0 4px 6px -1px rgb(0 0 0 / 0.4), 0 2px 4px -2px rgb(0 0 0 / 0.4)',
              lg: '0 10px 15px -3px rgb(0 0 0 / 0.4), 0 4px 6px -4px rgb(0 0 0 / 0.4)',
              xl: '0 20px 25px -5px rgb(0 0 0 / 0.4), 0 8px 10px -6px rgb(0 0 0 / 0.4)',
              '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.6)',
              inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.3)',
            },
            semantic: undefined as any,
          },
          borders: undefined as any,
          motion: undefined as any,
          zIndex: undefined as any,
          opacity: undefined as any,
        },
      },
    ],
    default: 'light',
    followSystem: true,
    userSelectable: true,
    storageKey: 'rses-color-scheme',
  },
};
