apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rses-cms
  namespace: rses-cms
  labels:
    app.kubernetes.io/name: rses-cms
  annotations:
    # Uncomment for nginx ingress controller
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # nginx.ingress.kubernetes.io/websocket-services: "rses-cms"
    #
    # Uncomment for cert-manager TLS
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: rses-cms.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rses-cms
                port:
                  name: http
  # Uncomment for TLS
  # tls:
  #   - hosts:
  #       - rses-cms.example.com
  #     secretName: rses-cms-tls
